language: go

dist: bionic

addons:
  apt:
    packages:
      - gccgo-6
    sources:
      - ubuntu-toolchain-r-test

install: true

matrix:
  include:
    - go: 1.13.x
      env: 
        - GO111MODULE=on
    - go: tip
      env: 
        - GO111MODULE=on
  allow_failures:
    - go: tip

before_script:
  - gccgo-6 --version
  
script:
  - make goveralls
  - make build
  - ./bin/statsd-http-proxy --version
